# Generated by Django 3.2.17 on 2023-02-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policyID', models.CharField(default='', max_length=100)),
                ('assetID', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
