# Generated by Django 3.2.17 on 2023-02-22 07:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nftcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checker',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 7, 11, 2, 50206, tzinfo=utc)),
        ),
    ]
