# Generated by Django 3.2.17 on 2023-02-23 04:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nftcheck', '0002_checker_time_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 23, 4, 0, 43, 601849, tzinfo=utc)),
        ),
    ]
