# Generated by Django 3.2.17 on 2023-02-11 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='')),
                ('buyer', models.CharField(default='', max_length=25)),
                ('seller', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.CharField(default='0x...', max_length=100)),
                ('seller_id', models.CharField(default='0x...', max_length=100)),
                ('contract_address', models.CharField(default='0x...', max_length=100)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.transaction')),
            ],
        ),
    ]
